export const GET_NOTICE_BY_SOURCE_REQUEST = "GET_NOTICE_BY_SOURCE_REQUEST";
export const GET_NOTICE_BY_SOURCE_SUCCESS = "GET_NOTICE_BY_SOURCE_SUCCESS";
export const GET_NOTICE_BY_SOURCE_FAIL = "GET_NOTICE_BY_SOURCE_FAIL";