export const POST_ASSIGNMENT_REQUEST = "POST_ASSIGNMENT_REQUEST";
export const POST_ASSIGNMENT_SUCCESS = "POST_ASSIGNMENT_SUCCESS";
export const POST_ASSIGNMENT_FAIL = "POST_ASSIGNMENT_FAIL";

export const POST_TEST_REQUEST = "POST_TEST_REQUEST";
export const POST_TEST_SUCCESS = "POST_TEST_SUCCESS";
export const POST_TEST_FAIL = "POST_TEST_FAIL";