export const POST_ASSIGNMENT_REQUEST = "POST_ASSIGNMENT_REQUEST";
export const POST_ASSIGNMENT_SUCCESS = "POST_ASSIGNMENT_SUCCESS";
export const POST_ASSIGNMENT_FAIL = "POST_ASSIGNMENT_FAIL";
export const POST_ASSIGNMENT_RESET = "POST_ASSIGNMENT_RESET";

export const POST_TEST_REQUEST = "POST_TEST_REQUEST";
export const POST_TEST_SUCCESS = "POST_TEST_SUCCESS";
export const POST_TEST_FAIL = "POST_TEST_FAIL";
export const POST_TEST_RESET = "POST_TEST_RESET";

export const GET_ASSIGNMENT_BY_COURSE_REQUEST = "GET_ASSIGNMENT_BY_COURSE_REQUEST";
export const GET_ASSIGNMENT_BY_COURSE_SUCCESS = "GET_ASSIGNMENT_BY_COURSE_SUCCESS";
export const GET_ASSIGNMENT_BY_COURSE_FAIL = "GET_ASSIGNMENT_BY_COURSE_FAIL";

export const GET_ASSIGNMENT_BY_ID_REQUEST = "GET_ASSIGNMENT_BY_ID_REQUEST";
export const GET_ASSIGNMENT_BY_ID_SUCCESS = "GET_ASSIGNMENT_BY_ID_SUCCESS";
export const GET_ASSIGNMENT_BY_ID_FAIL = "GET_ASSIGNMENT_BY_ID_FAIL";

export const GET_ASSIGNMENTTAKER_BY_ID_REQUEST = "GET_ASSIGNMENTTAKER_BY_ID_REQUEST";
export const GET_ASSIGNMENTTAKER_BY_ID_SUCCESS = "GET_ASSIGNMENTTAKER_BY_ID_SUCCESS";
export const GET_ASSIGNMENTTAKER_BY_ID_FAIL = "GET_ASSIGNMENTTAKER_BY_ID_FAIL";

export const GET_ASSIGNMENTTAKER_BY_IT_ID_REQUEST = "GET_ASSIGNMENTTAKER_BY_IT_ID_REQUEST";
export const GET_ASSIGNMENTTAKER_BY_IT_ID_SUCCESS = "GET_ASSIGNMENTTAKER_BY_IT_ID_SUCCESS";
export const GET_ASSIGNMENTTAKER_BY_IT_ID_FAIL = "GET_ASSIGNMENTTAKER_BY_IT_ID_FAIL";

export const GET_ASSIGNMENT_BY_STAFF_ID_REQUEST = "GET_ASSIGNMENT_BY_STAFF_ID_REQUEST";
export const GET_ASSIGNMENT_BY_STAFF_ID_SUCCESS = "GET_ASSIGNMENT_BY_STAFF_ID_SUCCESS";
export const GET_ASSIGNMENT_BY_STAFF_ID_FAIL = "GET_ASSIGNMENT_BY_STAFF_ID_FAIL";

export const EDIT_ASSIGNMENT_REQUEST = "EDIT_ASSIGNMENT_REQUEST";
export const EDIT_ASSIGNMENT_SUCCESS = "EDIT_ASSIGNMENT_SUCCESS";
export const EDIT_ASSIGNMENT_FAIL = "EDIT_ASSIGNMENT_FAIL";
export const EDIT_ASSIGNMENT_RESET = "EDIT_ASSIGNMENT_RESET";

export const DELETE_ASSIGNMENT_REQUEST = "DELETE_ASSIGNMENT_REQUEST";
export const DELETE_ASSIGNMENT_SUCCESS = "DELETE_ASSIGNMENT_SUCCESS";
export const DELETE_ASSIGNMENT_FAIL = "DELETE_ASSIGNMENT_FAIL";
export const DELETE_ASSIGNMENT_RESET = "DELETE_ASSIGNMENT_RESET";

export const GET_TEST_BY_COURSE_REQUEST = "GET_TEST_BY_COURSE_REQUEST";
export const GET_TEST_BY_COURSE_SUCCESS = "GET_TEST_BY_COURSE_SUCCESS";
export const GET_TEST_BY_COURSE_FAIL = "GET_TEST_BY_COURSE_FAIL";

export const GET_TEST_BY_ID_REQUEST = "GET_TEST_BY_ID_REQUEST";
export const GET_TEST_BY_ID_SUCCESS = "GET_TEST_BY_ID_SUCCESS";
export const GET_TEST_BY_ID_FAIL = "GET_TEST_BY_ID_FAIL";

export const GET_TEST_BY_SOURCE_REQUEST = "GET_TEST_BY_SOURCE_REQUEST";
export const GET_TEST_BY_SOURCE_SUCCESS = "GET_TEST_BY_SOURCE_SUCCESS";
export const GET_TEST_BY_SOURCE_FAIL = "GET_TEST_BY_SOURCE_FAIL";

export const GET_TESTTAKER_BY_ID_REQUEST = "GET_TESTTAKER_BY_ID_REQUEST";
export const GET_TESTTAKER_BY_ID_SUCCESS = "GET_TESTTAKER_BY_ID_SUCCESS";
export const GET_TESTTAKER_BY_ID_FAIL = "GET_TESTTAKER_BY_ID_FAIL";

export const EDIT_TEST_REQUEST = "EDIT_TEST_REQUEST";
export const EDIT_TEST_SUCCESS = "EDIT_TEST_SUCCESS";
export const EDIT_TEST_FAIL = "EDIT_TEST_FAIL";
export const EDIT_TEST_RESET = "EDIT_TEST_RESET";

export const DELETE_TEST_REQUEST = "DELETE_TEST_REQUEST";
export const DELETE_TEST_SUCCESS = "DELETE_TEST_SUCCESS";
export const DELETE_TEST_FAIL = "DELETE_TEST_FAIL";
export const DELETE_TEST_RESET = "DELETE_TEST_RESET";

export const EDIT_ASSIGNMENTTAKER_REQUEST = "EDIT_ASSIGNMENTTAKER_REQUEST";
export const EDIT_ASSIGNMENTTAKER_SUCCESS = "EDIT_ASSIGNMENTTAKER_SUCCESS";
export const EDIT_ASSIGNMENTTAKER_FAIL = "EDIT_ASSIGNMENTTAKER_FAIL";
export const EDIT_ASSIGNMENTTAKER_RESET = "EDIT_ASSIGNMENTTAKER_RESET";
