export const GET_SCOPE_REQUEST = "GET_SCOPE_REQUEST";
export const GET_SCOPE_SUCCESS = "GET_SCOPE_SUCCESS";
export const GET_SCOPE_FAIL = "GET_SCOPE_FAIL";

export const GET_NOTICE_REQUEST = "GET_NOTICE_REQUEST";
export const GET_NOTICE_SUCCESS = "GET_NOTICE_SUCCESS";
export const GET_NOTICE_FAIL = "GET_NOTICE_FAIL";

export const GET_NOTICE_BY_ID_REQUEST = "GET_NOTICE_BY_ID_REQUEST";
export const GET_NOTICE_BY_ID_SUCCESS = "GET_NOTICE_BY_ID_SUCCESS";
export const GET_NOTICE_BY_ID_FAIL = "GET_NOTICE_BY_ID_FAIL";

export const POST_NOTICE_REQUEST = "POST_NOTICE_REQUEST";
export const POST_NOTICE_SUCCESS = "POST_NOTICE_SUCCESS";
export const POST_NOTICE_FAIL = "POST_NOTICE_FAIL";
export const POST_NOTICE_RESET = "POST_NOTICE_RESET";

export const EDIT_NOTICE_REQUEST = "EDIT_NOTICE_REQUEST";
export const EDIT_NOTICE_SUCCESS = "EDIT_NOTICE_SUCCESS";
export const EDIT_NOTICE_FAIL = "EDIT_NOTICE_FAIL";
export const EDIT_NOTICE_RESET = "EDIT_NOTICE_RESET";

export const DELETE_NOTICE_REQUEST = "DELETE_NOTICE_REQUEST";
export const DELETE_NOTICE_SUCCESS = "DELETE_NOTICE_SUCCESS";
export const DELETE_NOTICE_FAIL = "DELETE_NOTICE_FAIL";
export const DELETE_NOTICE_RESET = "DELETE_NOTICE_RESET";