export {default as Home} from "./Auth/Login/index";
export {default as ForgotPassword} from "../screens/Auth/ForgetPassword/index";
export {default as ConfirmPassword} from "../screens/Auth/ConfirmPassword/index";
export {default as DashBoard} from "../screens/Dashboard/index";
export {default as BasicProfile} from "./Profile/BasicInformation/index";
export {default as EditBasicProfile} from "./Profile/BasicInformation/editBasicInformation";
export {default as BioData} from "./Profile/Biodata/index";
export {default as AcademyData} from "./Profile/academyData/index";
export {default as EditAcademyData} from "./Profile/academyData/editAcademy";
export {default as Editbiodata} from "./Profile/Biodata/editbiodata";
export {default as HealthData} from "./Profile/Health/index";
export {default as EditHealthdata} from "./Profile/Health/editHealthdata";
export {default as FamilyData} from "./Profile/FamilyData/index"
export {default as Editfamilydata} from "./Profile/FamilyData/editfamilydata"
export {default as AvailableCourses} from "./Courses/index";
export {default as CourseRegisteration} from "./Courses/courseRegisteration";
export {default as TestList} from "./Test/index";
export {default as StartPage} from "./Test/startpage";
export {default as TestScreen} from "./Test/testscreen";
export {default as ProfilePicture} from "./Profile/ProfileImage/index"
