export {default as Home} from "./Auth/Login/index";
export {default as ForgotPassword} from "../screens/Auth/ForgetPassword/index";
export {default as ConfirmPassword} from "../screens/Auth/ConfirmPassword/index";
export {default as DashBoard} from "./Student/Dashboard/index";
export {default as BasicProfile} from "../screens/Student/Profile/BasicInformation";
export {default as EditBasicProfile} from "../screens/Student/Profile/BasicInformation/editBasicInformation";
export {default as BioData} from "../screens/Student/Profile/Biodata";
export {default as AcademyData} from "../screens/Student/Profile/academyData";
export {default as EditAcademyData} from "../screens/Student/Profile/academyData/editAcademy"
export {default as Editbiodata} from "../screens/Student/Profile/Biodata/editbiodata";
export {default as HealthData} from "../screens/Student/Profile/Health";
export {default as EditHealthdata} from "../screens/Student/Profile/Health/editHealthdata";
export {default as FamilyData} from "../screens/Student/Profile/FamilyData"
export {default as Editfamilydata} from "../screens/Student/Profile/FamilyData/editfamilydata"
export {default as AvailableCourses} from "../screens/Student/Courses";
export {default as CourseRegisteration} from "../screens/Student/Courses";
export {default as TestList} from "./Student/Test/index";
export {default as StartPage} from "./Student/Test/startpage";
export {default as TestScreen} from "./Student/Test/testscreen";
export {default as ProfilePicture} from "./Student/Profile/ProfileImage/index"
export {default as LecturerProfile} from "./Staff/Profile";
export {default as EditLecturerProfile} from "./Staff/Profile/Editprofile"
export {default as Assignment} from "./Staff/Assesement/assignment/index";
export {default as AssignmentQuestionBank} from "./Staff/Assesement/assignment/questionBank"
export {default as LecturerTest} from "./Staff/Assesement/Test/index"
export {default as TestqustionBank} from "./Staff/Assesement/Test/testquestionBank"
export {default as RegisteredCourses } from "./Student/Courses/courseRegisteration"
export {default as Result} from "./Student/Results"