// export const QUESTION_REQUEST = "QUESTION_REQUEST";
// export const QUESTION_SUCCESS = "QUESTION_SUCCESS";
// export const QUESTION_FAIL = "QUESTION_FAIL";
// export const RESPONSE_REQUEST = "RESPONSE_REQUEST";
// export const RESPONSE_SUCCESS = "RESPONSE_SUCCESS";
// export const RESPONSE_FAIL = "RESPONSE_FAIL";