export const STUDENT_LOGIN_REQUEST = "STUDENT_LOGIN_REQUEST";
export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS";
export const STUDENT_LOGIN_FAIL = "STUDENT_LOGIN_FAIL";
export const STUDENT_LOGIN_RESET = "STUDENT_LOGIN_RESET";
export const STUDENT_LOGOUT = "STUDENT_LOGOUT";


export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAIL = "FORGET_PASSWORD_FAIL";
export const FORGET_PASSWORD_RESET = "FORGET_PASSWORD_RESET";

export const CONFIRM_PASSWORD_REQUEST = "CONFIRM_PASSWORD_REQUEST";
export const CONFIRM_PASSWORD_SUCCESS = "CONFIRM_PASSWORD_SUCCESS";
export const CONFIRM_PASSWORD_FAIL = "CONFIRM_PASSWORD_FAIL";
export const CONFIRM_PASSWORD_RESET = "CONFIRM_PASSWORD_RESET";

export const LECTURER_LOGIN_REQUEST = "LECTURER_LOGIN_REQUEST";
export const LECTURER_LOGIN_SUCCESS = "LECTURER_LOGIN_SUCCESS";
export const LECTURER_LOGIN_FAIL = "LECTURER_LOGIN_FAIL";
export const LECTURER_LOGIN_RESET = "LECTURER_LOGIN_RESET";
export const LECTURER_LOGOUT = "LECTURER_LOGOUT";


export const LECTURER_FORGET_PASSWORD_REQUEST = "LECTURER_FORGET_PASSWORD_REQUEST";
export const LECTURER_FORGET_PASSWORD_SUCCESS = "LECTURER_FORGET_PASSWORD_SUCCESS";
export const LECTURER_FORGET_PASSWORD_FAIL = "LECTURER_FORGET_PASSWORD_FAIL";
export const LECTURER_FORGET_PASSWORD_RESET = "LECTURER_FORGET_PASSWORD_RESET";

export const LECTURER_CONFIRM_PASSWORD_REQUEST = "LECTURER_CONFIRM_PASSWORD_REQUEST";
export const LECTURER_CONFIRM_PASSWORD_SUCCESS = "LECTURER_CONFIRM_PASSWORD_SUCCESS";
export const LECTURER_CONFIRM_PASSWORD_FAIL = "LECTURER_CONFIRM_PASSWORD_FAIL";
export const LECTURER_CONFIRM_PASSWORD_RESET = "LECTURER_CONFIRM_PASSWORD_RESET";