export const GET_COURSE_REQUEST = "GET_COURSE_REQUEST";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const GET_COURSE_FAIL = "GET_COURSE_FAIL";

export const POST_COURSE_REQUEST = "POST_COURSE_REQUEST";
export const POST_COURSE_SUCCESS = "POST_COURSE_SUCCESS";
export const POST_COURSE_FAIL = "POST_COURSE_FAIL";
export const POST_COURSE_RESET = "POST_COURSE_RESET";

export const GET_SEMESTER_REQUEST = "GET_SEMESTER_REQUEST";
export const GET_SEMESTER_SUCCESS = "GET_SEMESTER_SUCCESS";
export const GET_SEMESTER_FAIL = "GET_SEMESTER_FAIL";

export const GET_SESSION_REQUEST = "GET_SESSION_REQUEST";
export const GET_SESSION_SUCCESS = "GET_SESSION_SUCCESS";
export const GET_SESSION_FAIL = "GET_SESSION_FAIL";

export const POST_ADDCOURSE_REQUEST = "POST_ADDCOURSE_REQUEST";
export const POST_ADDCOURSE_SUCCESS = "POST_ADDCOURSE_SUCCESS";
export const POST_ADDCOURSE_FAIL = "POST_ADDCOURSE_FAIL";
export const POST_ADDCOURSE_RESET = "POST_ADDCOURSE_RESET";
