export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const CREATE_STUDENT_REQUEST = "CREATE_STUDENT_REQUEST";
export const CREATE_STUDENT_FAIL = "CREATE_STUDENT_FAIL";
export const CREATE_STUDENT_RESET = "CREATE_STUDENT_RESET";
