export const EDIT_STUDENTBYID_REQUEST = "EDIT_STUDENTBYID_REQUEST";
export const EDIT_STUDENTBYID_SUCCESS = "EDIT_STUDENTBYID_SUCCESS";
export const EDIT_STUDENTBYID_FAIL = "EDIT_STUDENTBYID_FAIL";
export const EDIT_STUDENTBYID_RESET = "EDIT_STUDENTBYID_RESET";
