export const CREATE_FACULTY_REQUEST = "CREATE_FACULTY_REQUEST";
export const CREATE_FACULTY_SUCCESS = "CREATE_FACULTY_SUCCESS";
export const CREATE_FACULTY_FAIL = "CREATE_FACULTY_FAIL";
export const CREATE_FACULTY_RESET = "CREATE_FACULTY_RESET";
