export const TOTAL_STUDENT_REQUEST = "TOTAL_STUDENT_REQUEST";
export const TOTAL_STUDENT_SUCCESS = "TOTAL_STUDENT_SUCCESS";
export const TOTAL_STUDENT_FAIL = "TOTAL_STUDENT_FAIL";

export const TOTAL_STAFF_REQUEST = "TOTAL_STAFF_REQUEST";
export const TOTAL_STAFF_SUCCESS = "TOTAL_STAFF_SUCCESS";
export const TOTAL_STAFF_FAIL = "TOTAL_STAFF_FAIL";
