export const POST_NOTICE_REQUEST = "POST_NOTICE_REQUEST";
export const POST_NOTICE_SUCCESS = "POST_NOTICE_SUCCESS";
export const POST_NOTICE_FAIL = "POST_NOTICE_FAIL";
export const POST_NOTICE_RESET = "POST_NOTICE_RESET";

export const GET_NOTICE_REQUEST = "GET_NOTICE_REQUEST";
export const GET_NOTICE_SUCCESS = "GET_NOTICE_SUCCESS";
export const GET_NOTICE_FAIL = "GET_NOTICE_FAIL";

export const POST_INFORMATION_REQUEST = "POST_INFORMATION_REQUEST";
export const POST_INFORMATION_SUCCESS = "POST_INFORMATION_SUCCESS";
export const POST_INFORMATION_FAIL = "POST_INFORMATION_FAIL";
export const POST_INFORMATION_RESET = "POST_INFORMATION_RESET";

export const IMAGE_INFORMATION_REQUEST = "IMAGE_INFORMATION_REQUEST";
export const IMAGE_INFORMATION_SUCCESS = "IMAGE_INFORMATION_SUCCESS";
export const IMAGE_INFORMATION_FAIL = "IMAGE_INFORMATION_FAIL";
export const IMAGE_INFORMATION_RESET = "IMAGE_INFORMATION_RESET";
