export const GET_SCOPE_REQUEST = "GET_SCOPE_REQUEST";
export const GET_SCOPE_SUCCESS = "GET_SCOPE_SUCCESS";
export const GET_SCOPE_FAIL = "GET_SCOPE_FAIL";

export const GET_INFORMATION_REQUEST = "GET_INFORMATION_REQUEST";
export const GET_INFORMATION_SUCCESS = "GET_INFORMATION_SUCCESS";
export const GET_INFORMATION_FAIL = "GET_INFORMATION_FAIL";
