export const USERS_DATA_REQUEST = "USERS_DATA_REQUEST";
export const USERS_DATA_SUCCESS = "USERS_DATA_SUCCESS";
export const USERS_DATA_FAIL = "USERS_DATA_FAIL";
export const USERS_DATA_RESET = "USERS_DATA_RESET";
