

export const EDITPROFILE_REQUEST = "EDITPROFILE_REQUEST";
export const EDITPROFILE_SUCCESS = "EDITPROFILE_SUCCESS";
export const EDITPROFILE_FAIL = "EDITPROFILE_FAIL";
export const EDITPROFILE_RESET = "EDITPROFILE_RESET";

export const PROFILE_PICTURE_REQUEST = "PROFILE_PICTURE_REQUEST";
export const PROFILE_PICTURE_SUCCESS = "PROFILE_PICTURE_SUCCESS";
export const PROFILE_PICTURE_FAIL = "PROFILE_PICTURE_FAIL";
export const PROFILE_PICTURE_RESET = "PROFILE_PICTURE_RESET";

