export const STUDENT_LOGIN_REQUEST = "STUDENT_LOGIN_REQUEST";
export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS";
export const STUDENT_LOGIN_FAIL = "STUDENT_LOGIN_FAIL";
export const STUDENT_LOGIN_RESET = "STUDENT_LOGIN_RESET";
export const STUDENT_LOGOUT = "STUDENT_LOGOUT";

export const STUDENT_DETAILS_REQUEST = "STUDENT_DETAILS_REQUEST";
export const STUDENT_DETAILS_SUCCESS = "STUDENT_DETAILS_SUCCESS";
export const STUDENT_DETAILS_FAIL = "STUDENT_DETAILS_FAIL";

export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAIL = "FORGET_PASSWORD_FAIL";
export const FORGET_PASSWORD_RESET = "FORGET_PASSWORD_RESET";

export const CONFIRM_PASSWORD_REQUEST = "CONFIRM_PASSWORD_REQUEST";
export const CONFIRM_PASSWORD_SUCCESS = "CONFIRM_PASSWORD_SUCCESS";
export const CONFIRM_PASSWORD_FAIL = "CONFIRM_PASSWORD_FAIL";
export const CONFIRM_PASSWORD_RESET = "CONFIRM_PASSWORD_RESET";

export const EDITPROFILE_REQUEST = "EDITPROFILE_REQUEST";
export const EDITPROFILE_SUCCESS = "EDITPROFILE_SUCCESS";
export const EDITPROFILE_FAIL = "EDITPROFILE_FAIL";
export const EDITPROFILE_RESET = "EDITPROFILE_RESET";

export const NOTICE_REQUEST = "NOTICE_REQUEST";
export const NOTICE_SUCCESS = "NOTICE_SUCCESS";
export const NOTICE_FAIL = "NOTICE_FAIL";
