

export const EDITPROFILE_REQUEST = "EDITPROFILE_REQUEST";
export const EDITPROFILE_SUCCESS = "EDITPROFILE_SUCCESS";
export const EDITPROFILE_FAIL = "EDITPROFILE_FAIL";
export const EDITPROFILE_RESET = "EDITPROFILE_RESET";

export const NOTICE_REQUEST = "NOTICE_REQUEST";
export const NOTICE_SUCCESS = "NOTICE_SUCCESS";
export const NOTICE_FAIL = "NOTICE_FAIL";
