export const STUDENT_LOGIN_REQUEST = "STUDENT_LOGIN_REQUEST";
export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS";
export const STUDENT_LOGIN_FAIL = "STUDENT_LOGIN_FAIL";
export const STUDENT_LOGIN_RESET = "STUDENT_LOGIN_RESET";
export const STUDENT_LOGOUT = "STUDENT_LOGOUT";

export const STUDENT_DETAILS_REQUEST = "STUDENT_DETAILS_REQUEST";
export const STUDENT_DETAILS_SUCCESS = "STUDENT_DETAILS_SUCCESS";
export const STUDENT_DETAILS_FAIL = "STUDENT_DETAILS_FAIL";
