export const GET_ASSIGNMENT_BY_STUDENT_ID_REQUEST = "GET_ASSIGNMENT_BY_STUDENT_ID_REQUEST";
export const GET_ASSIGNMENT_BY_STUDENT_ID_SUCCESS = "GET_ASSIGNMENT_BY_STUDENT_ID_SUCCESS";
export const GET_ASSIGNMENT_BY_STUDENT_ID_FAIL = "GET_ASSIGNMENT_BY_STUDENT_ID_FAIL";

export const POST_ASSIGNMENT_RESPONSE_REQUEST = "POST_ASSIGNMENT_RESPONSE_REQUEST";
export const POST_ASSIGNMENT_RESPONSE_SUCCESS = "POST_ASSIGNMENT_RESPONSE_SUCCESS";
export const POST_ASSIGNMENT_RESPONSE_FAIL = "POST_ASSIGNMENT_RESPONSE_FAIL";
export const POST_ASSIGNMENT_RESPONSE_RESET = "POST_ASSIGNMENT_RESPONSE_RESET";